slam_toolbox:
  ros__parameters:
    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link

    # Topics
    scan_topic: /scan

    # Mode
    mode: mapping

    # Timing
    transform_publish_period: 0.05
    map_update_interval: 1.0

    # Lidar model
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    # Loop closure (important)
    do_loop_closing: true
    loop_search_maximum_distance: 5.0

    # Scan matching
    use_scan_matching: true
    use_scan_barycenter: true

    # Performance (Pi-friendly)
    max_laser_range: 8.0
    throttle_scans: 1

    publish_tf: true
