- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "odom"
  gz_topic_name: "odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/wheel_encoders"
  gz_topic_name: "wheel_encoders"
  ros_type_name: "std_msgs/msg/Float64MultiArray"
  gz_type_name: "ignition.msgs.Float64MultiArray"
  direction: GZ_TO_ROS
