ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    # Frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Output
    odometry_frame: odom
    publish_tf: true
    publish_acceleration: false

    # ---- ODOMETRY INPUT (wheel odom) ----
    odom0: /odom
    odom0_config: [
        true,
        true,
        false, # x, y, z
        false,
        false,
        false, # roll, pitch, yaw  (leave yaw false)
        true,
        true,
        false, # vx, vy, vz
        false,
        false,
        false, # vroll, vpitch, vyaw
        false,
        false,
        false,
      ]

    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # ---- IMU INPUT ----
    imu0: /imu_with_covariances
    imu0_config: [
        false,
        false,
        false, # x, y, z
        false,
        false,
        true, # roll, pitch, yaw (yaw used)
        false,
        false,
        false, # vx, vy, vz
        false,
        false,
        true, # vroll, vpitch, vyaw (gyro z)
        false,
        false,
        false, # ax, ay, az
      ]
    imu0_queue_size: 50
    imu0_differential: false
    imu0_relative: true

    # IMPORTANT for IMUs
    imu0_remove_gravitational_acceleration: true
