ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    publish_acceleration: false

    # -------------------------
    # Wheel odom
    # -------------------------
    odom0: /odom
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # Fuse x, y, vx, vy from wheel odom. Do NOT fuse yaw from wheels.
    odom0_config: [
        true,
        true,
        false, # x, y, z
        false,
        false,
        false, # roll, pitch, yaw
        true,
        true,
        false, # vx, vy, vz
        false,
        false,
        false, # vroll, vpitch, vyaw
        false,
        false,
        false, # ax, ay, az
      ]

    # -------------------------
    # IMU
    # -------------------------
    imu0: /imu_with_covariances
    imu0_queue_size: 50
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true

    # Fuse yaw + gyro-z only
    imu0_config: [
        false,
        false,
        false, # x, y, z
        false,
        false,
        true, # roll, pitch, yaw
        false,
        false,
        false, # vx, vy, vz
        false,
        false,
        true, # vroll, vpitch, vyaw
        false,
        false,
        false, # ax, ay, az
      ]
